theme = "ayu_dark"

[editor]
bufferline = "multiple"
text-width = 120
end-of-line-diagnostics = "hint"
true-color = true

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "error"

[editor.lsp]
display-inlay-hints	= true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = ["version-control"]
right = ["diagnostics", "selections", "position", "primary-selection-length", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"

[editor.cursor-shape]
insert = "bar"

# [keys.normal]
# C-g = [
#   ":write-all",
#   ":new",
#   ":insert-output lazygit",
#   ":buffer-close!",
#   ":redraw",
#   ":reload-all"
#
