[[language]]
name = "rust"
auto-format = true

[language-server.rust-analyzer]
config = { cargo = { allFeatures = true }}

[[language]]
name = "go"
roots = ["go.work", "go.mod"]
auto-format = true
formatter = ["gofmt"]
comment-token = "//"
language-servers = [ "gopls" ]
